---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# XQUEUE
XQUEUE_HTTP_PORT: '8040'
XQUEUE_RABBITMQ_TLS: false

# CERTS
CERTS_QUEUE_URL: "http://localhost:{{ XQUEUE_HTTP_PORT }}"

# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "%%MYSQL_MASTER_IP%%"
XQUEUE_MYSQL_HOST: "%%MYSQL_MASTER_IP%%"
XQUEUE_MYSQL_PORT: "%%MYSQL_MASTER_PORT%%"

EDXAPP_MYSQL_HOST: "%%MYSQL_MASTER_IP%%"
EDXAPP_MYSQL_PORT: "%%MYSQL_MASTER_PORT%%"

# When bootstrapping multiple VMSS (especially on different versions like dogwood & ficus), we see a case where
# one VMSS seeds memcache with keys used by both versions of the VMSS. The values for those keys are only right for one version of the VMSS
# causing the other version of the VMSS to break. 

# As a fix, we will support 2 targets for memcache when supporting multiple version of VMSS, giving each VMSS access to its own memcache
# It is assumed that the memcache application is already installed on the specified server with 'MEMCACHE_SERVER_IP'
EDXAPP_MEMCACHE: ["%%MEMCACHE_SERVER_IP%%:11211"]

FORUM_MONGO_HOSTS:
  - "%%MONGO_SERVER_IP_PREFIX%%11"
  - "%%MONGO_SERVER_IP_PREFIX%%12"
  - "%%MONGO_SERVER_IP_PREFIX%%13"
EDXAPP_MONGO_HOSTS: "%%MONGO_SERVER_LIST%%"
EDXAPP_MONGO_PORT: 27017
EDXAPP_MONGO_REPLICA_SET: "%%MONGO_REPLICASET_NAME%%"

MONGO_USERS:
  - user: "{{ FORUM_MONGO_USER }}"
    password: "{{ FORUM_MONGO_PASSWORD }}"
    database: cs_comments_service
    roles: readWrite
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: edxapp
    roles: readWrite

RABBIT_USERS:
  - name: 'admin'
    password: "{{ RABBIT_ADMIN_PASSWORD }}"
  - name: 'edx'
    password: "{{ XQUEUE_RABBITMQ_PASS }}"
  - name: 'celery'
    password: "{{ EDXAPP_CELERY_PASSWORD }}"

# Configure discussion forum settings
FORUM_SINATRA_ENV: "production"
FORUM_RACK_ENV: "production"
MONGO_REPLICASET_NAME: '%%MONGO_REPLICASET_NAME%%'

# Configure mysql database
EDXAPP_MYSQL_USER_ADMIN: '%%MYSQL_ADMIN_USER%%'
EDXAPP_MYSQL_PASSWORD_ADMIN: '%%MYSQL_ADMIN_PASSWORD%%'
EDXAPP_MYSQL_USER: '%%MYSQL_USER%%'
EDXAPP_MYSQL_PASSWORD: "%%EDXAPP_MYSQL_PASSWORD%%"
COMMON_MYSQL_MIGRATE_USER: "{{ EDXAPP_MYSQL_USER_ADMIN }}"
COMMON_MYSQL_MIGRATE_PASS: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"

COMMON_HTPASSWD_PASS: '%%COMMON_HTPASSWD_PASS%%'
COMMON_HTPASSWD_USER: '%%COMMON_HTPASSWD_USER%%'
COMMON_MONGO_READ_ONLY_PASS: '%%COMMON_MONGO_READ_ONLY_PASS%%'
COMMON_MYSQL_ADMIN_PASS: '%%COMMON_MYSQL_ADMIN_PASS%%'
COMMON_MYSQL_READ_ONLY_PASS: '%%COMMON_MYSQL_READ_ONLY_PASS%%'

# Required for configuring mysql host for Programs playbook
PROGRAMS_DATABASE_HOST: "{{ EDXAPP_MYSQL_HOST }}"
PROGRAMS_DATABASE_PORT: "{{ EDXAPP_MYSQL_PORT }}"

# Required for 'Mysql | Ensure Anonymous user(s) does not exist' check
MYSQL_ADMIN_USER: "{{ EDXAPP_MYSQL_USER_ADMIN }}"
MYSQL_ADMIN_PASSWORD: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"

EDXAPP_MYSQL_CLOUD_SERVER_NAME: '%%EDXAPP_MYSQL_CLOUD_SERVER_NAME%%'
MYSQL_SERVER_FQDN: "{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}.mysql.database.azure.com"
EDXAPP_MYSQL_HOST: "{{ MYSQL_SERVER_FQDN }}"
XQUEUE_MYSQL_HOST: "{{ MYSQL_SERVER_FQDN }}"

AZURE_MYSQL_SSL_CA: '/etc/ssl/certs/Baltimore_CyberTrust_Root.pem'
EDXAPP_MYSQL_OPTIONS:
  ssl:
    ca: '{{ AZURE_MYSQL_SSL_CA }}'

XQUEUE_MYSQL_OPTIONS:
  ssl:
    ca: '{{ AZURE_MYSQL_SSL_CA }}'

JOURNALS_ENABLED: true
SANDBOX_ENABLE_RABBITMQ: true


# qualify user names with host name for azure mysql
EDXAPP_MYSQL_CSMH_USER: "edxapp_cmsh001@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
EDXAPP_MYSQL_USER_ADMIN: "lexoxamysqladmin@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
XQUEUE_MYSQL_USER: "xqueue001@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
EDXAPP_MYSQL_USER: "edxapp001@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
ANALYTICS_PIPELINE_OUTPUT_DATABASE_USER: "edxapp001@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"

# fillers - if necessary, provide passwords
HIVE_METASTORE_DATABASE_USER: "hive@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
CREDENTIALS_MYSQL_USER: "credentials@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
DISCOVERY_MYSQL_USER: "discovery@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
JOURNALS_MYSQL_USER: "journals@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
VEDA_WEB_FRONTEND_MYSQL_USER: "vedaweb@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"

NGINX_SSL_CERTIFICATE: %%NGINX_SSL_CERTIFICATE%%
NGINX_SSL_KEY: %%NGINX_SSL_KEY%%

# storage uploads
STORAGE_TYPE: "azure"
AZURE_STORAGE_PROVIDER: "storages.backends.azure_storage.AzureStorage"
EDXAPP_DEFAULT_FILE_STORAGE: "django.core.files.storage.FileSystemStorage"
EDXAPP_AZURE_ACCOUNT_NAME: "%%AZURE_ACCOUNT_NAME%%"
EDXAPP_AZURE_ACCOUNT_KEY: "%%AZURE_ACCOUNT_KEY%%"
EDXAPP_AZURE_CONTAINER: "uploads"
EDXAPP_GRADE_STORAGE_TYPE: "azure"
EDXAPP_GRADE_STORAGE_CLASS: "{{ AZURE_STORAGE_PROVIDER }}"

# Video Image Settings
EDXAPP_VIDEO_IMAGE_SETTINGS:
  VIDEO_IMAGE_MAX_BYTES : 2097152
  VIDEO_IMAGE_MIN_BYTES : 2048
  STORAGE_CLASS : "{{ AZURE_STORAGE_PROVIDER }}"
  STORAGE_KWARGS:
    account_name: "{{ EDXAPP_AZURE_ACCOUNT_NAME }}"
    account_key: "{{ EDXAPP_AZURE_ACCOUNT_KEY }}"
    azure_container: "{{ EDXAPP_AZURE_CONTAINER }}"
    azure_ssl: True
  DIRECTORY_PREFIX: "video-images/"


nginx_sites: [certs, cms, lms, forum, xqueue]

# Configure email addresses
EDXAPP_BUGS_EMAIL: "%%EDXAPP_EMAIL_BUGS%%"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "%%EDXAPP_EMAIL_BULK_FROM%%"
EDXAPP_CONTACT_EMAIL: "%%EDXAPP_EMAIL_CONTACT%%"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "%%EDXAPP_EMAIL_FEEDBACK%%"
EDXAPP_DEFAULT_FROM_EMAIL: "%%EDXAPP_EMAIL_DEFAULT_FROM%%"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "%%EDXAPP_EMAIL_PAYMENT_SUPPORT%%"
EDXAPP_PRESS_EMAIL: "%%EDXAPP_EMAIL_PRESS%%"
EDXAPP_DEFAULT_SERVER_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_TECH_SUPPORT_EMAIL: "%%EDXAPP_EMAIL_TECH_SUPPORT%%"
EDXAPP_UNIVERSITY_EMAIL: "%%EDXAPP_EMAIL_UNIVERSITY%%"

# Secure session cookie
EDXAPP_SESSION_COOKIE_SECURE: "%%NGINX_ENABLE_SSL%%"
SECRET_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
EDXAPP_EDXAPP_SECRET_KEY: "%%EDXAPP_EDXAPP_SECRET_KEY%%"
EDXAPP_LMS_SEGMENT_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
EDXAPP_CMS_SEGMENT_KEY: "{{ EDXAPP_EDXAPP_SECRET_KEY }}"
EDXAPP_ENABLE_COOKIE_CONSENT: %%EDXAPP_ENABLE_COOKIE_CONSENT%%

# Whitelists of allowed host domains
EDXAPP_LMS_ALLOWED_HOSTS: [%%EDXAPP_LMS_ALLOWED_HOSTS%%]
EDXAPP_CMS_ALLOWED_HOSTS: [%%EDXAPP_CMS_ALLOWED_HOSTS%%]

# newrelic
NEWRELIC_INFRASTRUCTURE_LICENSE_KEY: "%%NEWRELIC_INFRASTRUCTURE_LICENSE_KEY%%"
COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE: "%%COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE%%"

# Service passwords
ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD: "%%ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD%%"
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE: "%%ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE%%"
CREDENTIALS_MYSQL_PASSWORD: "%%CREDENTIALS_MYSQL_PASSWORD%%"
DISCOVERY_EMAIL_HOST_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"
DISCOVERY_MYSQL_PASSWORD: "%%DISCOVERY_MYSQL_PASSWORD%%"
ECOMMERCE_BROKER_PASSWORD: "%%ECOMMERCE_BROKER_PASSWORD%%"
ECOMMERCE_DATABASE_PASSWORD: "%%ECOMMERCE_DATABASE_PASSWORD%%"
ECOMMERCE_WORKER_BROKER_PASSWORD: "%%ECOMMERCE_WORKER_BROKER_PASSWORD%%"
EDXAPP_MYSQL_CSMH_PASSWORD: "%%EDXAPP_MYSQL_CSMH_PASSWORD%%"
EDXAPP_MYSQL_PASSWORD_READ_ONLY: "%%EDXAPP_MYSQL_PASSWORD_READ_ONLY%%"
FLOWER_BROKER_PASSWORD: "%%FLOWER_BROKER_PASSWORD%%"
HIVE_METASTORE_DATABASE_PASSWORD: "%%HIVE_METASTORE_DATABASE_PASSWORD%%"
INSIGHTS_DATABASE_PASSWORD: "%%INSIGHTS_DATABASE_PASSWORD%%"
INSIGHTS_EMAIL_HOST_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"
JENKINS_ANALYTICS_GITHUB_CREDENTIAL_PASSPHRASE: "%%JENKINS_ANALYTICS_GITHUB_CREDENTIAL_PASSPHRASE%%"
JENKINS_ANALYTICS_USER_PASSWORD_PLAIN: "%%JENKINS_ANALYTICS_USER_PASSWORD_PLAIN%%"
MARIADB_CLUSTER_PASSWORD_ADMIN: "%%MARIADB_CLUSTER_PASSWORD_ADMIN%%"

NOTIFIER_EMAIL_PASS: "%%NOTIFIER_EMAIL_PASSWORD%%"
NOTIFIER_USER_SERVICE_HTTP_AUTH_PASS: "%%NOTIFIER_USER_SERVICE_HTTP_AUTH_PASS%%"
POSTFIX_QUEUE_EXTERNAL_SMTP_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"
REDIS_PASSWORD: "%%REDIS_PASSWORD%%"
SPLUNKFORWARDER_PASSWORD: "%%SPLUNKFORWARDER_PASSWORD%%"
SPLUNK_SMTP_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"
SPLUNK_SSL_PASSWORD: "%%SPLUNK_SSL_PASSWORD%%"
SWIFT_LOG_SYNC_PASSWORD: "%%SWIFT_LOG_SYNC_PASSWORD%%"

XQUEUE_BASIC_AUTH_PASSWORD: "%%XQUEUE_BASIC_AUTH_PASSWORD%%"
XQUEUE_BASIC_AUTH_USER: "%%XQUEUE_BASIC_AUTH_USER%%"
XQUEUE_MYSQL_PASSWORD: "%%XQUEUE_MYSQL_PASSWORD%%"

MONGO_ADMIN_PASSWORD: "%%MONGO_ADMIN_PASSWORD%%"

# Settings
EDXAPP_ENABLE_THIRD_PARTY_AUTH: %%EDXAPP_ENABLE_THIRD_PARTY_AUTH%%
EDXAPP_ENABLE_OAUTH2_PROVIDER: %%EDXAPP_ENABLE_OAUTH2_PROVIDER%%
EDXAPP_ENABLE_SYSADMIN_DASHBOARD: %%EDXAPP_ENABLE_SYSADMIN_DASHBOARD%%
EDXAPP_ENABLE_MOBILE_REST_API: %%EDXAPP_ENABLE_MOBILE_REST_API%%
EDXAPP_ENABLE_CSMH_EXTENDED: %%EDXAPP_ENABLE_CSMH_EXTENDED%%
EDXAPP_PREVIEW_LMS_BASE: %%EDXAPP_PREVIEW_LMS_BASE%%

# Enable/Disable Maintenance Page for Nginx (false by default)
NGINX_EDXAPP_ENABLE_MAINTENANCE: %%NGINX_EDXAPP_ENABLE_MAINTENANCE%%

# Course Discovery
EDXAPP_ENABLE_COURSE_DISCOVERY: %%EDXAPP_ENABLE_COURSE_DISCOVERY%%

MONGO_ADMIN_USER: "%%MONGO_ADMIN_USER%%"
