---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "10.0.0.16"
XQUEUE_MYSQL_HOST: "10.0.0.16"
EDXAPP_MYSQL_HOST: "10.0.0.16"
EDXAPP_MEMCACHE: ["10.0.0.16:11211"]
MONGO_BIND_IP: "0.0.0.0"
FORUM_MONGO_HOSTS: ["%%MONGO_REPLICASET_NAME%%/10.0.0.11,10.0.0.12,10.0.0.13"]
EDXAPP_MONGO_HOSTS: ["%%MONGO_REPLICASET_NAME%%/10.0.0.11,10.0.0.12,10.0.0.13"]
EDXAPP_MONGO_USE_SSL: False

# Configure mongo database
EDXAPP_MONGO_USER: '%%MONGO_USER%%'
EDXAPP_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'
FORUM_MONGO_USER: '%%MONGO_USER%%'
FORUM_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'

# Configure mysql database
EDXAPP_MYSQL_USER_ADMIN: '%%MYSQL_ADMIN_USER%%'
EDXAPP_MYSQL_PASSWORD_ADMIN: '%%MYSQL_ADMIN_PASSWORD%%'
EDXAPP_MYSQL_USER: '%%MYSQL_USER%%'
EDXAPP_MYSQL_PASSWORD: '%%MYSQL_PASSWORD%%'

# Configure DNS for site and email links
EDXAPP_LMS_SITE_NAME: "%%LMS_URL%%"
EDXAPP_CMS_SITE_NAME: "%%CMS_URL%%"
EDXAPP_PREVIEW_SITE_NAME: "%%PREVIEW_URL%%
EDXAPP_LMS_BASE: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}"
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"

EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443

EDXAPP_LMS_PREVIEW_NGINX_PORT: 18020
EDXAPP_LMS_PREVIEW_SSL_NGINX_PORT: 48020
EDXAPP_LMS_PREVIEW_SSL_NGINX_FRONTEND_PORT: 443

EDXAPP_CMS_NGINX_PORT: 18010
EDXAPP_CMS_SSL_NGINX_PORT: 48010
EDXAPP_CMS_SSL_NGINX_FRONTEND_PORT: 443

NGINX_ENABLE_SSL: %%NGINX_ENABLE_SSL%%
NGINX_REDIRECT_TO_HTTPS: %%NGINX_ENABLE_SSL%%
NGINX_SSL_CERTIFICATE: %%NGINX_SSL_CERTIFICATE%%
NGINX_SSL_KEY: %%NGINX_SSL_KEY%%
