---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# XQUEUE
XQUEUE_HTTP_PORT: '8040'
XQUEUE_RABBITMQ_TLS: false

# CERTS
CERTS_QUEUE_URL: "http://localhost:{{ XQUEUE_HTTP_PORT }}"

# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "%%MYSQL_MASTER_IP%%"
XQUEUE_MYSQL_HOST: "%%MYSQL_MASTER_IP%%"
XQUEUE_MYSQL_PORT: "%%MYSQL_MASTER_PORT%%"

EDXAPP_MYSQL_HOST: "%%MYSQL_MASTER_IP%%"
EDXAPP_MYSQL_PORT: "%%MYSQL_MASTER_PORT%%"

# When bootstrapping multiple VMSS (especially on different versions like dogwood & ficus), we see a case where
# one VMSS seeds memcache with keys used by both versions of the VMSS. The values for those keys are only right for one version of the VMSS
# causing the other version of the VMSS to break. 

# As a fix, we will support 2 targets for memcache when supporting multiple version of VMSS, giving each VMSS access to its own memcache
# It is assumed that the memcache application is already installed on the specified server with 'MEMCACHE_SERVER_IP'
EDXAPP_MEMCACHE: ["%%MEMCACHE_SERVER_IP%%:11211"]

FORUM_MONGO_HOSTS:
  - "%%MONGO_SERVER_IP_PREFIX%%11"
  - "%%MONGO_SERVER_IP_PREFIX%%12"
  - "%%MONGO_SERVER_IP_PREFIX%%13"
EDXAPP_MONGO_HOSTS: ["%%MONGO_REPLICASET_NAME%%/%%MONGO_SERVER_LIST%%"]

# Configure discussion forum settings
FORUM_SINATRA_ENV: "production"
FORUM_RACK_ENV: "production"
MONGO_REPLICASET_NAME: '%%MONGO_REPLICASET_NAME%%'

# Required for configuring mysql host for Programs playbook
PROGRAMS_DATABASE_HOST: "{{ EDXAPP_MYSQL_HOST }}"
PROGRAMS_DATABASE_PORT: "{{ EDXAPP_MYSQL_PORT }}"

NGINX_SSL_CERTIFICATE: %%NGINX_SSL_CERTIFICATE%%
NGINX_SSL_KEY: %%NGINX_SSL_KEY%%

# storage uploads
EDXAPP_DEFAULT_FILE_STORAGE: "storages.backends.azure_storage.AzureStorage"
EDXAPP_AZURE_ACCOUNT_NAME: "%%AZURE_ACCOUNT_NAME%%"
EDXAPP_AZURE_ACCOUNT_KEY: "%%AZURE_ACCOUNT_KEY%%"
EDXAPP_AZURE_CONTAINER: "uploads"
EDXAPP_GRADE_STORAGE_TYPE: "azure"
EDXAPP_GRADE_STORAGE_CLASS: "openedx.core.storage.AzureStorageExtended"

# Add lms-preview to list sites to configure
nginx_sites: [certs, cms, lms, lms-preview, forum, xqueue]

# Configure email addresses
EDXAPP_BUGS_EMAIL: "%%EDXAPP_EMAIL_BUGS%%"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "%%EDXAPP_EMAIL_BULK_FROM%%"
EDXAPP_CONTACT_EMAIL: "%%EDXAPP_EMAIL_CONTACT%%"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "%%EDXAPP_EMAIL_FEEDBACK%%"
EDXAPP_DEFAULT_FROM_EMAIL: "%%EDXAPP_EMAIL_DEFAULT_FROM%%"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "%%EDXAPP_EMAIL_PAYMENT_SUPPORT%%"
EDXAPP_PRESS_EMAIL: "%%EDXAPP_EMAIL_PRESS%%"
EDXAPP_DEFAULT_SERVER_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_TECH_SUPPORT_EMAIL: "%%EDXAPP_EMAIL_TECH_SUPPORT%%"
EDXAPP_UNIVERSITY_EMAIL: "%%EDXAPP_EMAIL_UNIVERSITY%%"

# Secure session cookie
EDXAPP_SESSION_COOKIE_SECURE: "%%NGINX_ENABLE_SSL%%"
EDXAPP_EDXAPP_SECRET_KEY: "%%EDXAPP_EDXAPP_SECRET_KEY%%"
