---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "10.0.0.16"
XQUEUE_MYSQL_HOST: "10.0.0.16"
EDXAPP_MYSQL_HOST: "10.0.0.16"
EDXAPP_MEMCACHE: ["10.0.0.16:11211"]
MONGO_BIND_IP: "0.0.0.0"
FORUM_MONGO_HOSTS: ["%%MONGO_REPLICASET_NAME%%/10.0.0.11,10.0.0.12,10.0.0.13"]
EDXAPP_MONGO_HOSTS: ["%%MONGO_REPLICASET_NAME%%/10.0.0.11,10.0.0.12,10.0.0.13"]
EDXAPP_MONGO_USE_SSL: False

# Configure mongo database
EDXAPP_MONGO_USER: '%%MONGO_USER%%'
EDXAPP_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'

# Configure mysql database
EDXAPP_MYSQL_USER_ADMIN: '%%MYSQL_ADMIN_USER%%'
EDXAPP_MYSQL_PASSWORD_ADMIN: '%%MYSQL_ADMIN_PASSWORD%%'
EDXAPP_MYSQL_USER: '%%MYSQL_USER%%'
EDXAPP_MYSQL_PASSWORD: '%%MYSQL_PASSWORD%%'

# Configure DNS for site and email links
EDXAPP_LMS_SITE_NAME: "lms-%%CLUSTERNAME%%-%%DEPLOYMENT_SLOT%%.%%REGION%%.cloudapp.azure.com"
EDXAPP_CMS_SITE_NAME: "cms-%%CLUSTERNAME%%-%%DEPLOYMENT_SLOT%%.%%REGION%%.cloudapp.azure.com"
EDXAPP_LMS_BASE: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}"
EDXAPP_PREVIEW_LMS_BASE: "{{ EDXAPP_LMS_BASE }}"
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"