# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  FsDevFic:
    environment:
      - ONEBOX_PARAMS: "--branch Dev --Role Fullstack"
    <<: &sharedSetup
      # VM allows for "priveleged" containers.
      machine: true
      working_directory: ~/repo
      steps:
        - checkout
        - run: |
            docker pull solita/ubuntu-systemd:16.04
            docker run --rm --privileged -v /:/host solita/ubuntu-systemd:16.04 setup
            # Prepare cgroup on the host at /tmp/cgroup to avoid error: "failed to connect to bus: no such file or directory"
            sudo mkdir -p /tmp/cgroup/systemd && sudo mount -t cgroup systemd /tmp/cgroup/systemd -o ro,noexec,nosuid,nodev,none,name=systemd
        - run: |
            # Host entries from edx-configuration/playbooks/roles/local_dev/tasks/main.yml
            # "priveleged" to support THP changes in edx-configuration/playbooks/roles/mongo_3_2/tasks/main.yml
            docker run -d --name $(echo "$ONEBOX_PARAMS" | tr -d "-" | tr -d " ")  \
                          --add-host "localhost preview.localhost":127.0.0.1 \
                          --privileged \
                          --security-opt seccomp=unconfined \
                          --tmpfs /run \
                          --tmpfs /run/lock \
                          -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
                          -t solita/ubuntu-systemd:16.04
        - run:
            name: run tests
            command: source ./tests/deploy-onebox.sh
  DsDevFic:
    environment:
      - ONEBOX_PARAMS: "--branch Dev --Role Devstack"
    <<: *sharedSetup
  FsGink:
    environment:
      - ONEBOX_PARAMS: "--branch Ginkgo --Role Fullstack"
    <<: *sharedSetup
  DsGink:
    environment:
      - ONEBOX_PARAMS: "--branch Ginkgo --Role Devstack"
    <<: *sharedSetup
  FsEdxMaster:
    environment:
      - ONEBOX_PARAMS: "--branch Edx_master --Role Fullstack"
    <<: *sharedSetup
  DsEdxMaster:
    environment:
      - ONEBOX_PARAMS: "--branch Edx_master --Role Devstack"
    <<: *sharedSetup
  FsReleaseFic:
    environment:
      - ONEBOX_PARAMS: "--branch Release --Role Fullstack"
    <<: *sharedSetup
  DsReleaseFic:
    environment:
      - ONEBOX_PARAMS: "--branch Release --Role Devstack"
    <<: *sharedSetup
  FsMasterFic:
    environment:
      - ONEBOX_PARAMS: "--branch Master --Role Fullstack"
    <<: *sharedSetup
  DsMasterFic:
    environment:
      - ONEBOX_PARAMS: "--branch Master --Role Devstack"
    <<: *sharedSetup

# Jobs are sorted from longest duration to shortest (approximately)
# This generally means the shortest duration overall.
workflows:
  version: 2
  all:
    jobs:
      - FsGink:
          <<: &releaseFilter
            filters:
              branches:
                only:
                  - oxa/release.fic
      - DsEdxMaster:
          <<: *releaseFilter
      - DsGink:
          <<: *releaseFilter
      - DsDevFic:
          <<: &devFilter
            filters:
              branches:
                only:
                  - odf_branchFilters
      - DsReleaseFic:
          <<: *releaseFilter
      - DsMasterFic:
          <<: &masterFilter
            filters:
              branches:
                only:
                  - oxa/master.fic
      - FsDevFic:
          <<: *devFilter
      - FsReleaseFic:
          <<: *releaseFilter
      - FsMasterFic:
          <<: *masterFilter
