# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test1:
    environment:
      - ONEBOX_PARAMS: "--branch Dev --Role Fullstack"
    <<: &sharedSetup
      # VM allows for "priveleged" containers.
      machine: true
      working_directory: ~/repo
      steps:
        - checkout
        - run: |
            docker pull solita/ubuntu-systemd:16.04
            docker run --rm --privileged -v /:/host solita/ubuntu-systemd:16.04 setup
            # Prepare cgroup on the host at /tmp/cgroup to avoid error: "failed to connect to bus: no such file or directory"
            sudo mkdir -p /tmp/cgroup/systemd && sudo mount -t cgroup systemd /tmp/cgroup/systemd -o ro,noexec,nosuid,nodev,none,name=systemd
        - run: |
            # Host entries from edx-configuration/playbooks/roles/local_dev/tasks/main.yml
            # "priveleged" to support THP changes in edx-configuration/playbooks/roles/mongo_3_2/tasks/main.yml
            docker run -d --name $(echo "$ONEBOX_PARAMS" | tr -d "-" | tr -d " ")  \
                          --add-host "localhost preview.localhost":127.0.0.1 \
                          --privileged \
                          --security-opt seccomp=unconfined \
                          --tmpfs /run \
                          --tmpfs /run/lock \
                          -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
                          -t solita/ubuntu-systemd:16.04
        - run:
            name: run tests
            command: source ./tests/deploy-onebox.sh
  test2:
    environment:
      - ONEBOX_PARAMS: "--branch Dev --Role Devstack"
    <<: *sharedSetup
  test3:
    environment:
      - ONEBOX_PARAMS: "--branch Ginkgo --Role Fullstack"
    <<: *sharedSetup
  test4:
    environment:
      - ONEBOX_PARAMS: "--branch Ginkgo --Role Devstack"
    <<: *sharedSetup
  test5:
    environment:
      - ONEBOX_PARAMS: "--branch Edx_master --Role Fullstack"
    <<: *sharedSetup
  test6:
    environment:
      - ONEBOX_PARAMS: "--branch Edx_master --Role Devstack"
    <<: *sharedSetup

workflows:
  version: 2
  all:
    # Jobs are sorted from longest duration to shortest (approximately)
    # This generally means the shortest duration overall.
    jobs:
      # This one can take a little over two hours which is the timeout on circleci
      # If we want to re-nenable this then we'll need to do some "perf tuning"
      #- test5
      - test3
      - test6
      - test2
      - test4
      - test1
