---
# Sample Open edX on Azure configuration
# see: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml

EDXAPP_PLATFORM_NAME: "%%PLATFORM_NAME%%"

EDXAPP_TIME_ZONE: "America/Los_Angeles"

# Configure third-party auth
# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/
# see: https://github.com/MSOpenTech/edx-documentation/blob/master/en_us/install_operations/source/configuration/enable_sso.rst
#EDXAPP_ENABLE_THIRD_PARY_AUTH: true
#EDXAPP_ENABLE_OAUTH2_PROVIDER: true

# Password Policy Configuration
# AT least 8 characters. Must contain at least one lowercase, one uppercase and one symbol.
EDXAPP_PASSWORD_MIN_LENGTH: 8 
EDXAPP_PASSWORD_MAX_LENGTH: 75
EDXAPP_PASSWORD_COMPLEXITY: 
  UPPER: 1
  LOWER: 1
  PUNCTUATION: 1

EDXAPP_ENFORCE_PASSWORD_POLICY: true

# Adding Disclosure Notice to the marketing url link mapping
EDXAPP_MKTG_URL_LINK_MAP:
  DN: "dn"

# Country made required field in registration.
EDXAPP_REGISTRATION_EXTRA_FIELDS: 
  city: "hidden"
  country: "required"
  gender: "optional"
  goals: "optional"
  honor_code: "required"
  level_of_education: "optional"
  mailing_address: "hidden"
  year_of_birth: "hidden"


# Enable social sharing icons for courses. For now we are just enabling linkedin. 
# Facebook and Twitter is not enabled for now.
EDXAPP_SOCIAL_SHARING_SETTINGS:
  CERTIFICATE_FACEBOOK: false
  CERTIFICATE_LINKEDIN: true
  CERTIFICATE_TWITTER: false
  DASHBOARD_FACEBOOK: false
  DASHBOARD_LINKEDIN: true
  DASHBOARD_TWITTER: false


# Order of the social media links we want learners to see in the footer
# We can also add facebook, twitter, youtube, google_plus and reddit here later if we enable them in SOCIAL_SHARING_SETTINGS above
EDXAPP_SOCIAL_MEDIA_FOOTER_NAMES: [ "linkedin" ]


# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/feature_flags/feature_flag_index.html
EDXAPP_FEATURES:
  USE_CUSTOM_THEME: true
  #ENABLE_THIRD_PARTY_AUTH: "{{ EDXAPP_ENABLE_THIRD_PARTY_AUTH }}"
  #ENABLE_OAUTH2_PROVIDER: "{{ EDXAPP_ENABLE_OAUTH2_PROVIDER }}"
  ENABLE_SYSADMIN_DASHBOARD: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: false
  # PREVIEW_LMS_BASE must be localhost for course discovery to work with dns (openedx.slack - 9/14/16 @3:08pm)
  PREVIEW_LMS_BASE: "{{ EDXAPP_PREVIEW_SITE_NAME }}"
  DISABLE_COURSE_CREATION: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true
  ALLOW_HIDING_DISCUSSION_TAB: true
  CERTIFICATES_ENABLED: true
  CERTIFICATES_HTML_VIEW: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_VIDEO_UPLOAD_PIPELINE: true

# storage uploads
EDXAPP_DEFAULT_FILE_STORAGE: "storages.backends.azure_storage.AzureStorage"
EDXAPP_AZURE_ACCOUNT_NAME: "%%AZURE_ACCOUNT_NAME%%"
EDXAPP_AZURE_ACCOUNT_KEY: "%%AZURE_ACCOUNT_KEY%%"
EDXAPP_AZURE_CONTAINER: "uploads"
EDXAPP_GRADE_STORAGE_TYPE: "azure"
EDXAPP_GRADE_STORAGE_CLASS: "openedx.core.storage.AzureStorageExtended"
EDXAPP_GRADE_STORAGE_KWARGS:
  container: "reports"
EDXAPP_GRADE_STORAGE_CONTAINER: "reports"
  
# Configure email addresses
EDXAPP_BUGS_EMAIL: "microsoftlearning-bugs@microsoft.com"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "microsoftlearning-noreply@microsoft.com"
EDXAPP_CONTACT_EMAIL: "microsoftlearning-info@microsoft.com"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "microsoftlearning-feedback@microsoft.com"
EDXAPP_DEFAULT_FROM_EMAIL: "microsoftlearning-registration@microsoft.com"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "microsoftlearning-billing@microsoft.com"
EDXAPP_PRESS_EMAIL: "microsoftlearning-press@microsoft.com"
EDXAPP_DEFAULT_SERVER_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_TECH_SUPPORT_EMAIL: "microsoftlearning-technical@microsoft.com"
EDXAPP_UNIVERSITY_EMAIL: "microsoftlearning-university@microsoft.com"

EDXAPP_LTI_USER_EMAIL_DOMAIN: "lti.openedx.microsoft.com"

# Default log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
#EDXAPP_LOG_LEVEL: 'INFO'

# Add lms-preview to list sites to configure
nginx_sites: [certs, cms, lms, lms-preview, forum, xqueue]
