---
# Sample Open edX on Azure configuration
# see: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml

EDXAPP_PLATFORM_NAME: "%%PLATFORM_NAME%%"

EDXAPP_TIME_ZONE: "America/Los_Angeles"

EDXAPP_LMS_SITE_NAME: "%%CLUSTERNAME%%lms.%%REGION%%.cloudapp.azure.com"
EDXAPP_CMS_SITE_NAME: "%%CLUSTERNAME%%cms.%%REGION%%.cloudapp.azure.com"
EDXAPP_LMS_BASE: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}:18010"
EDXAPP_PREVIEW_LMS_BASE: "{{ EDXAPP_LMS_BASE }}"

# EDXAPP_SITE_NAME is used in many places like:
#   Activation link
#   Password reset link
#   Course live view link
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"

# Configure third-party auth
# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/
# see: https://github.com/MSOpenTech/edx-documentation/blob/master/en_us/install_operations/source/configuration/enable_sso.rst
#EDXAPP_ENABLE_THIRD_PARY_AUTH: true
#EDXAPP_ENABLE_OAUTH2_PROVIDER: true
 
# Country made required field in registration.
EDXAPP_REGISTRATION_EXTRA_FIELDS: 
  city: "hidden"
  country: "required"
  gender: "optional"
  goals: "optional"
  honor_code: "required"
  level_of_education: "optional"
  mailing_address: "hidden"
  year_of_birth: "hidden"


# Enable social sharing icons for courses. For now we are just enabling linkedin. 
# Facebook and Twitter is not enabled for now.
EDXAPP_SOCIAL_SHARING_SETTINGS:
  CERTIFICATE_FACEBOOK: false
  CERTIFICATE_LINKEDIN: true
  CERTIFICATE_TWITTER: false
  DASHBOARD_FACEBOOK: false
  DASHBOARD_LINKEDIN: true
  DASHBOARD_TWITTER: false


# Order of the social media links we want learners to see in the footer
# We can also add facebook, twitter, youtube, google_plus and reddit here later if we enable them in SOCIAL_SHARING_SETTINGS above
EDXAPP_SOCIAL_MEDIA_FOOTER_NAMES: [ "linkedin" ]


# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/feature_flags/feature_flag_index.html
EDXAPP_FEATURES:
  USE_CUSTOM_THEME: true
  #ENABLE_THIRD_PARTY_AUTH: "{{ EDXAPP_ENABLE_THIRD_PARTY_AUTH }}"
  #ENABLE_OAUTH2_PROVIDER: "{{ EDXAPP_ENABLE_OAUTH2_PROVIDER }}"
  ENABLE_SYSADMIN_DASHBOARD: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: true
  PREVIEW_LMS_BASE: "{{ EDXAPP_PREVIEW_LMS_BASE }}"
  DISABLE_COURSE_CREATION: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true

# Configure email addresses
EDXAPP_CONTACT_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_TECH_SUPPORT_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_BUGS_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_DEFAULT_FROM_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_DEFAULT_SERVER_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"

# Default log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
#EDXAPP_LOG_LEVEL: 'INFO'

EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443

EDXAPP_LMS_PREVIEW_NGINX_PORT: 18020
EDXAPP_CMS_NGINX_PORT: 18010
EDXAPP_CMS_SSL_NGINX_PORT: 48010

NGINX_ENABLE_SSL: %%NGINX_ENABLE_SSL%%
NGINX_REDIRECT_TO_HTTPS: %%NGINX_ENABLE_SSL%%
NGINX_SSL_CERTIFICATE: %%NGINX_SSL_CERTIFICATE%%
NGINX_SSL_KEY: %%NGINX_SSL_KEY%%
