---
# Copyright (c) Microsoft Corporation. All Rights Reserved.
# Licensed under the MIT license. See LICENSE file on the project webpage for details.

# Sample Open edX on Azure configuration
# see: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml

EDXAPP_PLATFORM_NAME: "Open edX on Azure"

EDXAPP_TIME_ZONE: "America/Los_Angeles"

# Configure DNS name based on the ARM template parameter
#EDXAPP_SITE_NAME: "{dnsLabelPrefix}.{region}.cloudapp.azure.com"
EDXAPP_LMS_SITE_NAME: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_CMS_SITE_NAME: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_LMS_BASE: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_SITE_NAME }}:18010"
EDXAPP_PREVIEW_LMS_BASE: "{{ EDXAPP_LMS_BASE }}"

# Configure third-party auth
# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/
# see: https://github.com/MSOpenTech/edx-documentation/blob/master/en_us/install_operations/source/configuration/enable_sso.rst
#EDXAPP_ENABLE_THIRD_PARY_AUTH: true
#EDXAPP_ENABLE_OAUTH2_PROVIDER: true


# Modifying Country or Region list. null means country is removed from the list. Others either country is a new added country or display name is changed.
EDXAPP_COUNTRIES_OVERRIDE:
  BO: "Bolivia"
  BQ: "Bonaire"
  VG: "British Virgin Islands"
  BN: "Brunei"
  CD: "Congo (DRC)"
  IR: null
  CB: null
  FK: "Falkland Islands"
  VA: null
  HK: "Hong Kong SAR"
  XJ: "Jan Mayen"
  KP: null
  KR: "Korea"
  XK: "Kosova"
  LA: "Laos"
  MO: "Macao SAR"
  MK: "Macedonia, FYRO"
  FM: "Micronesia"
  MD: "Moldova"
  PS: "Palestinian Authority"
  PN: "Pitcairn Island"
  RU: "Russia"
  XE: "Sint Eustatius"
  SX: "Sint Maarten"
  XS: "Saba"
  MF: "Saint Martin"
  SH: "St Helena, Ascension, Tristan da Cunha"
  SJ: "Svalbard"
  SD: null
  SY: null
  TW: "Taiwan"
  TZ: "Tanzania"
  UM: "U.S. Outlying Islands"
  VI: "U.S. Virgin Islands"
  US: "United States"
  GB: "United Kingdom"
  VE: "Venezuela"
  VN: "Vietnam"
  EH: null
 
# Country made required field in registration.
EDXAPP_REGISTRATION_EXTRA_FIELDS: 
  city: "hidden"
  country: "required"
  gender: "hidden"
  goals: "optional"
  honor_code: "required"
  level_of_education: "hidden"
  mailing_address: "hidden"
  year_of_birth: "hidden"


# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/feature_flags/feature_flag_index.html
EDXAPP_FEATURES:
  USE_CUSTOM_THEME: true
  #ENABLE_THIRD_PARTY_AUTH: "{{ EDXAPP_ENABLE_THIRD_PARTY_AUTH }}"
  #ENABLE_OAUTH2_PROVIDER: "{{ EDXAPP_ENABLE_OAUTH2_PROVIDER }}"
  ENABLE_SYSADMIN_DASHBOARD: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: true
  PREVIEW_LMS_BASE: "{{ EDXAPP_PREVIEW_LMS_BASE }}"
  DISABLE_COURSE_CREATION: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true

# Configure remote SMTP server
#EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
#EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
#EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
#EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# Configure email addresses
#EDXAPP_CONTACT_EMAIL: "email"
#EDXAPP_TECH_SUPPORT_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
#EDXAPP_BUGS_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
#EDXAPP_DEFAULT_FROM_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
#EDXAPP_DEFAULT_FEEDBACK_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
#EDXAPP_DEFAULT_SERVER_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"
#EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "{{ EDXAPP_CONTACT_EMAIL }}"

# Default log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
#EDXAPP_LOG_LEVEL: 'INFO'

EDXAPP_LMS_NGINX_PORT: 18000
EDXAPP_LMS_SSL_NGINX_PORT: 48000

EDXAPP_LMS_PREVIEW_NGINX_PORT: 18020
EDXAPP_CMS_NGINX_PORT: 18010
EDXAPP_CMS_SSL_NGINX_PORT: 48010

NGINX_ENABLE_SSL: %%NGINX_ENABLE_SSL%%
NGINX_REDIRECT_TO_HTTPS: True
NGINX_SSL_CERTIFICATE: /oxa/oxa-tools-config/nginx/cert/openedx.microsoft.com.crt
NGINX_SSL_KEY: /oxa/oxa-tools-config/nginx/cert/openedx.microsoft.com.key
