---
# Sample Open edX on Azure configuration
# see: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml

EDXAPP_PLATFORM_NAME: "%%PLATFORM_NAME%%"

EDXAPP_TIME_ZONE: "America/Los_Angeles"

# Superuser information
CREATE_SUPER_USER: %%CREATE_SUPER_USER%%
EDXAPP_SU_PASSWORD: "%%EDXAPP_SU_PASSWORD%%" 
EDXAPP_SU_EMAIL: "%%EDXAPP_SU_EMAIL%%"
EDXAPP_SU_USERNAME: "%%EDXAPP_SU_USERNAME%%"

# Enable Azure Active Directory OAuth2 Third Party Authentication
EDXAPP_AAD_CLIENT_ID: "%%EDXAPP_AAD_CLIENT_ID%%"
EDXAPP_AAD_SECURITY_KEY: "%%EDXAPP_AAD_SECURITY_KEY%%" 
EDXAPP_AAD_BUTTON_NAME: "%%EDXAPP_AAD_BUTTON_NAME%%"
EDXAPP_AAD_ENABLE: %%EDXAPP_ENABLE_THIRD_PARTY_AUTH%%

# Import Kitchen Sink Course Configuration
EDXAPP_IMPORT_KITCHENSINK_COURSE: %%EDXAPP_IMPORT_KITCHENSINK_COURSE%%

# Configure third-party auth
# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/
# see: https://github.com/MSOpenTech/edx-documentation/blob/master/en_us/install_operations/source/configuration/enable_sso.rst
#EDXAPP_ENABLE_THIRD_PARY_AUTH: true
#EDXAPP_ENABLE_OAUTH2_PROVIDER: true

# By defining COURSE_VISIBILITY keys we are allowing making course visible/invisible on course advanced settings the key
# 'Course Visibility In Catalog' 
# Defines the access permissions for showing the course in the course catalog. This can be set to one of three values: 
# 'both' (show in catalog and allow access to about page), 
# 'about' (only allow access to about page), 
# 'none' (do not show in catalog and do not allow access to an about page).
EDXAPP_COURSE_CATALOG_VISIBILITY_PERMISSION: "see_in_catalog"
EDXAPP_COURSE_ABOUT_VISIBILITY_PERMISSION: "see_about_page"

# Adding Disclosure Notice to the marketing url link mapping
EDXAPP_MKTG_URL_LINK_MAP:
  DN: "dn"

EDXAPP_RETIREMENT_STATES:
  - "PENDING"
  - "LOCKING_ACCOUNT"
  - "ERRORED"
  - "ABORTED"
  - "COMPLETE"

# Country made required field in registration.
EDXAPP_REGISTRATION_EXTRA_FIELDS: 
  city: "hidden"
  country: "hidden"
  disclosure_notice: "required"
  gender: "hidden"
  goals: "hidden"
  honor_code: "hidden"
  language: "hidden"
  level_of_education: "hidden"
  mailing_address: "hidden"
  terms_of_service: "required"
  year_of_birth: "hidden"  

# Enable social sharing icons for courses. For now we are just enabling linkedin. 
# Facebook and Twitter is not enabled for now.
EDXAPP_SOCIAL_SHARING_SETTINGS:
  CERTIFICATE_FACEBOOK: false
  CERTIFICATE_LINKEDIN: true
  CERTIFICATE_TWITTER: false
  DASHBOARD_FACEBOOK: false
  DASHBOARD_LINKEDIN: true
  DASHBOARD_TWITTER: false

# Order of the social media links we want learners to see in the footer
# We can also add facebook, twitter, youtube, google_plus and reddit here later if we enable them in SOCIAL_SHARING_SETTINGS above
EDXAPP_SOCIAL_MEDIA_FOOTER_NAMES: [ "linkedin" ]

# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/feature_flags/feature_flag_index.html
EDXAPP_FEATURES:  
  ENABLE_THIRD_PARTY_AUTH: %%EDXAPP_ENABLE_THIRD_PARTY_AUTH%%
  ENABLE_OAUTH2_PROVIDER: %%EDXAPP_ENABLE_OAUTH2_PROVIDER%%
  ENABLE_SYSADMIN_DASHBOARD: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: false
  # PREVIEW_LMS_BASE must be localhost for course discovery to work with dns (openedx.slack - 9/14/16 @3:08pm)
  PREVIEW_LMS_BASE: "%%PREVIEW_URL%%"
  DISABLE_COURSE_CREATION: true
  DISABLE_LIBRARY_CREATION: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true
  ALLOW_HIDING_DISCUSSION_TAB: true
  CERTIFICATES_ENABLED: true
  CERTIFICATES_HTML_VIEW: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_VIDEO_UPLOAD_PIPELINE: true
  ENABLE_MOBILE_REST_API: %%EDXAPP_ENABLE_MOBILE_REST_API%%
  OAUTH_ENFORCE_SECURE: %%OAUTH_ENFORCE_SECURE%%
  ENABLE_COMBINED_LOGIN_REGISTRATION: %%COMBINED_LOGIN_REGISTRATION%%
  # ENABLE_CSMH_EXTENDED: true
  ENABLE_LTI_PROVIDER: %%ENABLE_LTI_PROVIDER%%
  ALLOW_COURSE_STAFF_GRADE_DOWNLOADS: true
  ENABLE_AZURE_MEDIA_SERVICES_XBLOCK: %%ENABLE_AZURE_MEDIA_SERVICES_XBLOCK%%
  ENABLE_DISCUSSION_HOME_PANEL: true
  ENABLE_INSTRUCTOR_ANALYTICS: false
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_CORS_HEADERS: false
  ENABLE_CROSS_DOMAIN_CSRF_COOKIE: false
  ENABLE_COURSE_DISCOVERY: %%EDXAPP_ENABLE_COURSE_DISCOVERY%%
  ENABLE_CUSTOM_AUTH: %%EDXAPP_ENABLE_CUSTOM_AUTH%%
  ENABLE_COOKIE_CONSENT: %%EDXAPP_ENABLE_COOKIE_CONSENT%%
  
# Comprehensive Theming Configuration
THEMES_CODE_DIR: "%%THEMES_CODE_DIR%%"
EDXAPP_ENABLE_COMPREHENSIVE_THEMING: %%EDXAPP_ENABLE_COMPREHENSIVE_THEMING%%
EDXAPP_DEFAULT_SITE_THEME: "%%EDXAPP_DEFAULT_SITE_THEME%%"
EDXAPP_THEME_ENVIRONMENT: "%%ENVIRONMENT%%"
EDXAPP_COMPREHENSIVE_THEME_DIRS:
  - "{{ THEMES_CODE_DIR }}"

# Comprehensive Theming Configuration
EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO: "https://github.com/Microsoft/edx-theme/" 
EDXAPP_COMPREHENSIVE_THEME_VERSION: "%%EDXAPP_COMPREHENSIVE_THEME_VERSION%%"

THEMES_REPO: "edx-theme.git"
THEMES_VERSION: "{{ EDXAPP_COMPREHENSIVE_THEME_VERSION }}"
THEMES_REPOS:
  - PROTOCOL: "{{ THEMES_GIT_PROTOCOL }}"
    DOMAIN: "{{ THEMES_GIT_MIRROR }}"
    PATH: "microsoft"
    REPO: "{{ THEMES_REPO }}"
    VERSION: "{{ THEMES_VERSION }}"
    DESTINATION: "{{ THEMES_CODE_DIR }}"
    SSH_KEY: "{{ THEMES_GIT_IDENTITY }}"

ENABLE_CSMH_EXTENDED: %%EDXAPP_ENABLE_CSMH_EXTENDED%%
ENABLE_READING_FROM_MULTIPLE_HISTORY_TABLES: %%EDXAPP_ENABLE_READING_FROM_MULTIPLE_HISTORY_TABLES%%

# storage uploads
EDXAPP_GRADE_STORAGE_KWARGS:
  container: "reports"
EDXAPP_GRADE_STORAGE_CONTAINER: "reports"

# overriding the default value from 5 to 50. we don't want to stop the retry's at any point.  
EDXAPP_RETRY_ACTIVATION_EMAIL_MAX_ATTEMPTS: 50

# overriding the default value from 0.5 to 2. 
EDXAPP_RETRY_ACTIVATION_EMAIL_TIMEOUT: 2

# Security
EDXAPP_SESSION_INACTIVITY_TIMEOUT_IN_SECONDS: 1800
EDXAPP_X_FRAME_OPTIONS: "SAMEORIGIN"
NGINX_ENABLE_SSL: %%NGINX_ENABLE_SSL%%
NGINX_REDIRECT_TO_HTTPS: %%NGINX_ENABLE_SSL%%
EDXAPP_CSRF_COOKIE_SECURE: %%NGINX_ENABLE_SSL%%
EDXAPP_ENABLE_CONNECTION_LIMITING: %%EDXAPP_ENABLE_CONNECTION_LIMITING%%
EDXAPP_ENABLE_RATE_LIMITING: %%EDXAPP_ENABLE_RATE_LIMITING%%

EDXAPP_LTI_USER_EMAIL_DOMAIN: "lti.openedx.microsoft.com"

# Default log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
#EDXAPP_LOG_LEVEL: 'INFO'

# Cookies API url
EDXAPP_API_COOKIE_URL: "%%EDXAPP_COOKIE_API_URL%%"

# View live drop down for CMS
EDXAPP_ENABLE_MULTI_SITE_VIEWLIVE_DROPDOWN: "%%EDXAPP_ENABLE_MULTI_SITE_VIEWLIVE_DROPDOWN%%"
# Shared Mongo Settings
MONGO_BIND_IP: "0.0.0.0"
MONGO_PORT: 27017
EDXAPP_MONGO_USE_SSL: False
EDXAPP_MONGO_USER: '%%MONGO_USER%%'
EDXAPP_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'
mongo_admin_password: '{{ MONGO_ADMIN_PASSWORD }}'
COMMON_MONGO_READ_ONLY_USER: '{{ MONGO_ADMIN_USER }}'
COMMON_MONGO_READ_ONLY_PASS: '{{ MONGO_ADMIN_PASSWORD }}'

# Shared Forum Settings
FORUM_MONGO_DATABASE: "cs_comments_service"
FORUM_MONGO_PORT: "27017"
FORUM_MONGO_TAGS: !!null
FORUM_MONGO_USER: '%%MONGO_USER%%'
FORUM_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'
FORUM_MONGO_URL: "mongodb://{{ FORUM_MONGO_USER }}:{{ FORUM_MONGO_PASSWORD }}@{%- for host in FORUM_MONGO_HOSTS -%}{{ host }}:{{ FORUM_MONGO_PORT }}{%- if not loop.last -%},{%- endif -%}{%- endfor -%}/{{ FORUM_MONGO_DATABASE }}?replicaSet={{ MONGO_REPLICASET_NAME }}{%- if FORUM_MONGO_TAGS -%}&tags={{ FORUM_MONGO_TAGS }}{%- endif -%}"
FORUM_MONGO_USE_SSL: false

# Configure DNS for site and email links
EDXAPP_SITE_NAME: "%%LMS_URL%%"
EDXAPP_CMS_SITE_NAME: "%%CMS_URL%%"
EDXAPP_LMS_BASE: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}"

EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443

EDXAPP_LMS_PREVIEW_NGINX_PORT: 18020
EDXAPP_LMS_PREVIEW_SSL_NGINX_PORT: 48020
EDXAPP_LMS_PREVIEW_SSL_NGINX_FRONTEND_PORT: 443

EDXAPP_CMS_NGINX_PORT: 18010
EDXAPP_CMS_SSL_NGINX_PORT: 48010
EDXAPP_CMS_SSL_NGINX_FRONTEND_PORT: 443

CREDENTIALS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: %%EDXAPP_REDIRECT_IS_HTTPS%%
EDXAPP_REDIRECT_IS_HTTPS: %%EDXAPP_REDIRECT_IS_HTTPS%%
EDXAPP_ENABLE_CUSTOM_AUTH: %%EDXAPP_ENABLE_CUSTOM_AUTH%%

# Custom error message on NGINX error pages
NGINX_SERVER_RATE_LIMIT_ERROR_MSG: 'We have been notified of the error and we are actively working on restoring service.'
NGINX_SERVER_ERROR_MSG: 'We have been notified of the error and we are actively working on restoring service.'

EDXAPP_ONLY_THIRD_PARTY_AUTH: "%%EDXAPP_ONLY_THIRD_PARTY_AUTH%%"
EDXAPP_THIRD_PARTY_AUTH_BACKENDS:
  - "social_core.backends.google.GoogleOAuth2"
  - "social_core.backends.live.LiveOAuth2"
  - "social_core.backends.linkedin.LinkedinOAuth2"
  - "social_core.backends.facebook.FacebookOAuth2"
  - "social_core.backends.azuread.AzureADOAuth2"
  - "third_party_auth.saml.SAMLAuthBackend"
  - "third_party_auth.lti.LTIAuthBackend"

# Rabbitmq related credentials
RABBIT_ADMIN_PASSWORD: "%%RABBIT_ADMIN_PASSWORD%%"
EDXAPP_CELERY_PASSWORD: "%%EDXAPP_CELERY_PASSWORD%%"
XQUEUE_RABBITMQ_PASS: "%%XQUEUE_RABBITMQ_PASS%%"
RABBIT_USERS:
  - name: 'admin'
    password: "{{ RABBIT_ADMIN_PASSWORD }}"
  - name: 'edx'
    password: "{{ XQUEUE_RABBITMQ_PASS }}"
  - name: 'celery'
    password: "{{ EDXAPP_CELERY_PASSWORD }}"

#newrelic 
NEWRELIC_INFRASTRUCTURE_LICENSE_KEY:
COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE: "%%COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE%%"

#Insights
EDXAPP_ANALYTICS_DASHBOARD_URL: "%%EDXAPP_ANALYTICS_DASHBOARD_URL%%"

# Secret keys for Django Applicatons
ANALYTICS_API_SECRET_KEY: "%%ANALYTICS_API_SECRET_KEY%%"
CREDENTIALS_SECRET_KEY: "%%CREDENTIALS_SECRET_KEY%%"
DISCOVERY_SECRET_KEY: "%%DISCOVERY_SECRET_KEY%%"
ECOMMERCE_SECRET_KEY: "%%ECOMMERCE_SECRET_KEY%%"
EDX_NOTES_API_SECRET_KEY: "%%EDX_NOTES_API_SECRET_KEY%%"
EDXAPP_EDXAPP_SECRET_KEY: "%%EDXAPP_EDXAPP_SECRET_KEY%%"
EDXAPP_PROFILE_IMAGE_SECRET_KEY: "%%EDXAPP_PROFILE_IMAGE_SECRET_KEY%%"
INSIGHTS_SECRET_KEY: "%%INSIGHTS_SECRET_KEY%%"
NOTIFIER_LMS_SECRET_KEY: "%%NOTIFIER_LMS_SECRET_KEY%%"
FORUM_API_KEY: "%%FORUM_API_KEY%%"
EDXAPP_COMMENTS_SERVICE_KEY: '{{ FORUM_API_KEY }}'
NOTIFIER_COMMENT_SERVICE_API_KEY: '{{ FORUM_API_KEY }}'

# Azure keyvault configs 
EDXAPP_GET_SECRETS_FROM_AZURE_KEYVAULT: %%EDXAPP_GET_SECRETS_FROM_AZURE_KEYVAULT%%
EDXAPP_AZURE_MSI_REQUEST_URI: "%%EDXAPP_AZURE_MSI_REQUEST_URI%%"
EDXAPP_KEYVAULT_PAYLOAD: '%%EDXAPP_KEYVAULT_PAYLOAD%%'
EDXAPP_KEYVAULT_URL: "%%EDXAPP_KEYVAULT_URL%%"
EDXAPP_KEYVAULT_API_VERSION: "%%EDXAPP_KEYVAULT_API_VERSION%%"
EDXAPP_LMS_NON_SECURE_KEY_NAME: "%%EDXAPP_LMS_NON_SECURE_KEY_NAME%%"
EDXAPP_LMS_SECURE_KEY_NAME: "%%EDXAPP_LMS_SECURE_KEY_NAME%%"
EDXAPP_CMS_NON_SECURE_KEY_NAME: "%%EDXAPP_CMS_NON_SECURE_KEY_NAME%%"
EDXAPP_CMS_SECURE_KEY_NAME: "%%EDXAPP_CMS_SECURE_KEY_NAME%%"

EDXAPP_ENCRYPT_SESSION_KEY_USING_MD5: false

# EDX defaults course mode to Audit, this setting overrides that default
EDXAPP_COURSE_MODE_DEFAULTS":
    bulk_sku: null
    currency: "usd"
    description": null
    expiration_datetime: null
    min_price: 0
    name: "Honor"
    sku: null
    slug: "honor"
    suggested_prices: ""

# Enable/Disable SSL forwarding for nginx
# In some specific cases, requests being forwarded from nginx to gunicorn are downgraded to HTTP
# Enabling SSL forwarding forces SSL for those forwarded requests
EDXAPP_NGINX_ENABLE_SSL_FORWARDING: true