---
# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "127.0.0.1"
XQUEUE_MYSQL_HOST: "127.0.0.1"
EDXAPP_MYSQL_HOST: "127.0.0.1"
EDXAPP_MEMCACHE: ["127.0.0.1:11211"]
FORUM_MONGO_HOSTS:
  - "127.0.0.1"
EDXAPP_MONGO_HOSTS: ["127.0.0.1"]

# Configure discussion forum settings
FORUM_SINATRA_ENV: "development"
FORUM_RACK_ENV: "development"
MONGO_REPLICASET_NAME: ""

MONGO_USERS:
  - user: cs_comments_service
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: cs_comments_service
    roles: readWrite
  - user: edxapp
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: edxapp
    roles: readWrite
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: edxapp
    roles: readWrite

EDXAPP_PYTHON_SANDBOX: false

# storage
EDXAPP_GRADE_STORAGE_TYPE: "localfs"

nginx_sites: %%NGINX_SITES%%

# Configure email addresses
EDXAPP_BUGS_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_CONTACT_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_DEFAULT_FROM_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_PRESS_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_DEFAULT_SERVER_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_TECH_SUPPORT_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_UNIVERSITY_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_API_ACCESS_MANAGER_EMAIL: "%%PLATFORM_EMAIL%%"
EDXAPP_API_ACCESS_FROM_EMAIL: "%%PLATFORM_EMAIL%%"
