
- name: Configure OXA
  hosts: localhost
  vars:
    mysql_files_path: "{{ oxa_tools_path }}/playbooks/roles/mysql/files"
  sudo: True
  gather_facts: True
  roles:
    - { role: edxapp, tags: [ 'edxapp' ] }
    - { role: mongo, tags: [ 'mongo' ] }
    - { role: mysql, tags: [ 'mysql' ] }
